version: '3'
volumes:
  dados:
networks: 
  app:
  db:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - db
  front-end:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - app
    depends_on: 
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
      - app
      - db
      - fila
    depends_on: 
      - db
      - worker
      - queue
  worker:
    image: python:3.6
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks: 
      - fila
    depends_on: 
      - queue
  queue:
    image: redis:3.2
    networks: 
      - fila
