version: '3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Test123@"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts:/scripts
    command:
      - /bin/bash
      - -c 
      - |
        /opt/mssql/bin/sqlservr &

        sleep 30

        for foo in /scripts/*.sql
          do /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i $$foo
        done
        
        sleep infinity
